### ISSUE TITLE
Element not found by front end highlighting: color contrast issue in elementor 

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#103]
Page: https://amberhinds.com/consulting/

Code Snippet:
`<a href="#consulting-inquiry" class="elementor-button-link elementor-button elementor-size-xs" role="button"> <span class="elementor-button-content-wrapper"> <span class="elementor-button-text">lets chat</span> </span> </a> .elementor-1165 .elementor-element.elementor-element-3fce07d .elementor-button{font-family: "Oswald", Sans-serif; font-size: 16px; font-weight: 400; line-height: 1em; letter-spacing: 2px; fill: #222222; color: #222222; background-color: rgba(255, 255, 255, 0); padding: 0px 0px 0px 0px; }`

It's this:
<img width="1321" alt="Screen Shot 2023-02-09 at 1 58 19 PM" src="https://user-images.githubusercontent.com/13153456/217923681-e745e27c-86cb-457d-8f82-3bcf4617f796.png">

I think this is also a false positive on the color contrast because it's using rgba instead of a hex.

**Comment by territutich** [comment]
I have a similar issue. Should I put it on here, or add as a new issue?

**Comment by amberhinds** [comment]
@territutich can you add a comment here with the URL and the code snippet?  Thanks!

**Comment by territutich** [comment]
URL: https://wiseowlmarketing.com/learn/

Code Snippet:
`<a class="btn btn-primary" role="button" href="https://wiseowlmarketing.com/courses/happy-marketing-planner/" rel="bookmark">Enroll Now</a> .ld-course-list-items .ld_course_grid .btn-primary{color: white; background-color: #428bca; border-color: #357ebd; border-radius: 5px; padding: 15px; font-size: 18px!important; text-transform: uppercase; text-decoration: none; }`

I think it's referring to CSS for some pseudo-class, because the CSS referenced in the code snippet isn't the regular or :hover state for the link. I've added new CSS for the :active and :focus pseudo-classes, but I'm still seeing this on the backend, and "View on Page" gives the error "Accessibility Checker could not find the element on the page."

**Comment by SteveJonesDev** [comment]
The beta plugin is now successfully finding this element.

<img width="425" alt="Screen Shot 2023-04-07 at 5 42 22 PM" src="https://user-images.githubusercontent.com/2895788/230682560-184496a0-3d67-4025-9bc5-9b5d846e7c72.png">

There was a hotfix that went out in the product version of the plugin that addresses the false positives.

**Comment by territutich** [comment]
Quick question - I am still experiencing the issue I mentioned above. Should I add this as a new issue?

**Comment by amberhinds** [comment]
No, this was fixed for an upcoming release, but hasn't been released yet so
you're probably still seeing the issue on the beta you have.
