### ISSUE TITLE
A Video is Present duplicating issues

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#137]
One video is flagging twice, once with the figure and once with an iframe
<img width="1333" alt="Issue in backend" src="https://user-images.githubusercontent.com/13153456/231034600-9f0dcf89-c2bd-4b5d-ae30-0bdfa28df528.png">

<img width="1584" alt="Video on Page" src="https://user-images.githubusercontent.com/13153456/231034901-2d1bff3b-dd96-4047-a871-852329c43b20.png">

Page URL: https://roadwarriorprd.wpengine.com/wp-admin/post.php?post=9464&action=edit

**Comment by amberhinds** [comment]
Based on what I'm seeing with Front End Highlighting, I think it would be better to have the figure tag get flagged rather than the iframe if the iframe is in a figure.

**Comment by SteveJonesDev** [comment]
@vukvukovich  here is the first issue. Please submit a pull request to the master branch. Feel free to ask any questions you may have here.

Please disregard comments about Front End Highlighting as this feature hasn't been released yet. The goal of this issue is to have the figure tag get flagged rather than the iframe if the iframe is in a figure.

https://github.com/equalizedigital/accessibility-checker/blob/master/includes/rules/video_present.php
