### ISSUE TITLE
Front-End not ignoring Link Opens New Window or Tab even if ANWW is installed

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#189]
This warning doesn't show on the back end, but it does on the front end, even though they have Accessibility New Window Warnings installed and activated.

These should be excluded from the frontend too.
<img width="976" alt="Screen Shot 2023-06-23 at 9 21 45 AM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/47808f68-d7e7-4327-80a6-f251962cb14a">

**Comment by boonedev** [comment]
The switch to JS should fix this.

**Comment by amberhinds** [comment]
Is there any way that we can code a fix for this sooner?

**Comment by amberhinds** [comment]
@pattonwebz is this relevant to the other bugs you were working on?

**Comment by pattonwebz** [comment]
@amberhinds no this one isn't related but I did see this when working to solve those other ones and seems like the problem was related to the stored markup being different to what the highlighter sees after ANWW modifies it. I don't think it's a very complicated solve so I will take a look at this as soon as I'm free.

**Comment by SteveJonesDev** [comment]
Issue moved to our internal system.
