### ISSUE TITLE
Ability to link the Accessibility Page Footer link to a non WP page

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#23]
We had a user request that they be able to link their Accessibility Statement in the footer of their website to a now WP page (their accessibility statement is on their Magento store, not their WP page).  - Support ticket #980 for Pro plugin assigned to Steve currently.

Can we add a way for users to set any URL? Maybe the page select dropdown needs to change to a custom URL field or that can be present with the dropdown?

**Comment by SteveJonesDev** [comment]
I think switching the dropdown to an input field is the easiest and most flexible solution. Do you think this should be pushed as a hotfix now or for the next release?

**Comment by amberhinds** [comment]
Next release is okay.

**Comment by SteveJonesDev** [comment]
This has been completed. @amberhinds it's on the demo site for testing.

**Comment by amberhinds** [comment]
Do you know how it will impact people who already have it active?

**Comment by SteveJonesDev** [comment]
It takes that into account. The option used to be saved as a post ID. If a post ID is found it will convert it to the permalink otherwise it will use the new saved URL. On the demo site you can see on system info tab the option is still saved as the post ID but it's displaying the URL on the setting page and frontend.

**Comment by amberhinds** [comment]
Awesome, thank you so much!
