### ISSUE TITLE
Ignore Refreshes Page

### ISSUE THREAD

**Issue by markaplet** [equalizedigital/accessibility-checker#24]
Clicking the "Ignore" action link will initiate a page reload. The panel will expand revealing the comment form field, however the page is refreshed before text can be entered.  

I tested this issue in multiple environment including linux and windows with Divi Builder, and vanilla Wordpress with the same result.

**Comment by amberhinds** [comment]
Hi @markaplet, we cannot replicate the page refresh. Have you ruled out a plugin conflict?  When you saw it in "vanilla WordPress" was it the only active plugin and were you using a twenty-X theme?

**Comment by philwp** [comment]
I've been able to replicate the issue.  @markaplet thanks for reporting this.  

I'm seeing this happen on `edac-details-rule-title-arrow` as well.  I will need to test this, but I'm pretty sure this is because the `button` elements are causing the page reload.  `preventDefault()` needs to be used here.

**Comment by SteveJonesDev** [comment]
This has been fixed in version 1.0.13.
