### ISSUE TITLE
Ambiguous Link Text

### ISSUE THREAD

**Issue by markaplet** [equalizedigital/accessibility-checker#25]
The following link throws an "Ambiguous Anchor Text" error. 

`<a href="/city-of-palmdale-approved-station/" aria-label="Read more: City of Palmdale Approved Station">Read More</a>`

The above link is valid because it does have an aria-label attribute that contains both the text "read more" along with the article title.

**Comment by philwp** [comment]
Thanks @markaplet for bringing this to our attention.  We will definitely address this.  We should also add support for `aria-labelledby`

**Comment by philwp** [comment]
I think the best way to handle this is to pass whatever string a screen reader would reader here into the `ac_check_ambiguous_phrase` function (looks like the prefix needs to be fixed on that function)
So, if `aria-label` exists we can pass that into the function instead of `$a->plaintext` we can do the same for `aria-labelledby`

**Comment by SteveJonesDev** [comment]
This check has been improved to include ambiguous phrase checks on aria-label and aria-labelledby. The order of the logic is aria-label, aria-labelledby, plain text, and img alt. So if an aria-label is present on an element it will check that but if it's not it will move on to the next attribute which is aria-labelledby and so on. This will go out in the next minor release version 1.2.0.
