### ISSUE TITLE
Reading level not updating on the Readability tab.

### ISSUE THREAD

**Issue by SteveJonesDev** [equalizedigital/accessibility-checker#275]
Summary tab updates via Ajax:
![Screenshot 2023-09-08 at 10 07 37 AM](https://github.com/equalizedigital/accessibility-checker/assets/2895788/d604efd2-7c1a-48a8-be8e-3f84fa52c3b1)

The readability tab does not update via Ajax:
![Screenshot 2023-09-08 at 10 07 44 AM](https://github.com/equalizedigital/accessibility-checker/assets/2895788/ea4b2fe5-3bec-43fd-8f5a-b95d864f109d)

Refreshing the page shows the correct reading level:
![Screenshot 2023-09-08 at 10 10 07 AM](https://github.com/equalizedigital/accessibility-checker/assets/2895788/86d3c032-79c0-481b-a40b-e1acb8dd71e7)

Testing instructions:
1. Open a new post
2. Add text to the post
3. Publish post
4. View Summary and Readability tabs
5. Refresh the browser page

**Comment by boonedev** [comment]
There is a timing issue with the ajax calls:

edac_readability_ajax depends on edac_summary_ajax running and completing edac_summary before being called, otherwise edac_readability_ajax will return results based on the previously run edac_summary. 

This fix allows us to pass a js callback to edac_readability_ajax so we can run the edac_readability_ajax call after edax_summary_ajax is complete.
