### ISSUE TITLE
"This page has never been scanned!" warning or notice within front-end highlighting

### ISSUE THREAD

**Issue by christophermhinds** [equalizedigital/accessibility-checker#521]
If a user installs our plugin and immediately goes to the front-end and clicks on the accessibility widget, it will report zero errors and zero warnings for any page/post they load. We've had reports that users find this confusing.

I'd like to suggest adding a warning on the front-end highlighting widget that conditionally displays inside the widget if the page/post was never scanned by Accessibility Checker: 

**"This page has never been scanned! Save or update this page to initiate a scan."**

**Comment by SteveJonesDev** [comment]
@christophermhinds, have you been able to replicate this with the current version of the plugin? Not long ago we added a scan trigger from the frontend if the page hasn't been scanned.

**Comment by pattonwebz** [comment]
@SteveJonesDev I tested this last week and could reproduce it - but I am unable to nail down the exact reproduction steps because, as you say, a scan is triggered on the front end if the page isn't currently checked and it returns those scan results.

I do see a situation where it will say there are no issues if there is a generalised error (like the page being generated programmatically without any defined ID to assign issues to). I know that's a pretty uncommon edge case, but I think we likely won't differentiate between 'error', 'no data', and 'actually fine' rather than assuming all those cases actually mean no issues detected.

**Comment by christophermhinds** [comment]
Just seeing these comments. This was based on comments from a customer during a sales call and I did not attempt to replicate this myself. I was not aware that such a scan trigger existed in front-end highlighting. If we can't replicate, then this can probably be closed and chalk it up to user error.
