### ISSUE TITLE
"Null" issues reported for checks that are being disabled by a filter

### ISSUE THREAD

**Issue by christophermhinds** [equalizedigital/accessibility-checker#524]
### Please give us a description of what happened.

When a user has already run a scan and then adds a filter that disables a check, positives on disabled checks can still show up in our reports as a "null" value.

### Please describe what you expected to happen and why.

The expected result of disabling a check is that the disabled check would be filtered out everywhere, including in scan results.

### How can we reproduce this behavior?
1. Run a scan on a page where a specific check will trigger a positive result.
2. Disable the triggered check by adding a filter to the theme or functions file.
3. Go back to the report on that page and you should see a "null" value displaying in front-end and potentially other areas of our reports.

### Technical info

N/A

* Which browser is affected (or browsers): 
- [x] Internet Explorer
- [x] Edge
- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Brave

* Relevant plugins in case of a bug:

This is not a result of a plugin conflict.

* Tested with theme:

N/A

**Comment by pattonwebz** [comment]
I did some benchmarking on the impact of editing queries from the summary widget to avoid showing rules that have been filtered out since the last post scan and the impact is about 4% increase in query time. I don't think we should do anything in this pass to solve that because the impact is only on people who have filtered out a rule between last scan and not yet run a rescan.
![Screenshot from 2024-03-11 14-42-40](https://github.com/equalizedigital/accessibility-checker/assets/3902039/7709a737-6c9e-45fb-90ff-fe534c0cb635)

**Comment by SteveJonesDev** [comment]
I figured there would be a minor performance impact but thanks for being thorough and providing actual benchmarks! 

@christophermhinds, This has been fixed with [version 1.9.2](https://github.com/equalizedigital/accessibility-checker/releases/tag/v1.9.2).
