### ISSUE TITLE
Add Email Opt-in

### ISSUE THREAD

**Issue by SteveJonesDev** [equalizedigital/accessibility-checker#558]
Instead of an interstitial page, we should add a modal on the plugin page after every activation, that includes an Active Campaign opt-in. Use the Active Campaign form currently used in the plugin. We might be able to utilize the Media upload dialog popup but we need to ensure it's accessible.

![Screenshot 2024-03-28 at 1 56 11 PM](https://github.com/equalizedigital/accessibility-checker/assets/2895788/b6fc7a64-eaf1-4ce7-bced-f418cac2b146)

**Comment by christophermhinds** [comment]
@pattonwebz @SteveJonesDev 

🟡 I created a new "Editor" user to test this and trigger the modal. The modal appears as expected and works in the way one might expect. **However**, I did observe that I was able to "Tab" out of the modal on my keyboard and that there was no focus lock. I am not sure if we can control this since I know this is an ActiveCampaign embed, but wanted to flag it.

<img width="1669" alt="Screenshot 2024-04-30 at 11 04 08 AM" src="https://github.com/equalizedigital/accessibility-checker/assets/25856499/d73c93d9-9d95-49aa-8076-d6c60b191dab">

**Comment by pattonwebz** [comment]
There should be a focus trap for the modal. I'll double check it.

**Comment by SteveJonesDev** [comment]
I can confirm the focus trap isn't working.

**Comment by pattonwebz** [comment]
@SteveJonesDev I fixed that in the release branch. Can you pull and build the release branch and check if the focus trap is solved in it? https://github.com/equalizedigital/accessibility-checker/pull/596

**Comment by SteveJonesDev** [comment]
@pattonwebz It's working for me with the latest release build. Thanks!
