### ISSUE TITLE
Low-quality Alternative Text new keyword

### ISSUE THREAD

**Issue by SteveJonesDev** [equalizedigital/accessibility-checker#619]
A user reported the keyword `an image` not flagging Low-quality alternative text. 

Assess adding this keyword and the possibility of adding a filter.

**Comment by pattonwebz** [comment]
I looked at this with some test data and the reason that it isn't flagged for that tester is because the image is in a figure with a caption. When there's a caption we break early from the checks and no error is checked for https://github.com/equalizedigital/accessibility-checker/blob/1e20599f2c60e160dbff480001ee40819f889ae3/includes/rules/img_alt_invalid.php#L103

**Comment by SteveJonesDev** [comment]
Issue moved to our internal system.
