### ISSUE TITLE
Unexpected empty paragraph tag

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#666]
@pattonwebz can you investigate why this is flagging an empty paragraph tag warning?

`<p class="lockup"> <img src="https://2024.wpaccessibility.day/wp-content/themes/wp-a11y-day/assets/lockup.png" alt="WpA11yDay" width="250"> </p>// {{ .lockup }}`

<img width="1601" alt="Screenshot 2024-06-11 at 10 32 46 PM" src="https://github.com/equalizedigital/accessibility-checker/assets/13153456/556d7b2f-704d-4c99-b838-661b26e85d2f">

**Comment by pattonwebz** [comment]
@amberhinds This is happening because the first node inside the paragraph is whitespace. I had the check set up with the assumption that if the paragraph was not empty, then its first node would be another HTML tag.

I opened a PR that tweaks the check so that it does not matter if the paragraph content starts with whitespace or in what order the first text or HTML tag appears.
