### ISSUE TITLE
Improve Small Text rule logic

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-checker#8]
Currently, this rule is checking for font size using points and pixels and flags if both are less than or equal to 10.

This rule should be improved in the following ways:

1. Set font size for points to be <=13.
2. Add logic to get the base size and calculate em/rem sizing then flag if too small.

**Comment by SteveJonesDev** [comment]
I've added logic to account for point font sizes.

**Comment by SteveJonesDev** [comment]
Calculating em/rem is much more difficult and I'm not sure possible with the current structure of the plugin. We would need to get the browser default font setting and convert the em/rem size to pixels. Calculating the pixel size can be tricky as well because of inheritance. If the browser provides its default font size, it can be found via javascript using getComputedStyle.

For the HTML tag:
`window.getComputedStyle(document.body.parentNode);`

For the BODY tag:
`window.getComputedStyle(document.body);`

The problem with using javascript is the page scan is trigged via the server-side save_post hook and has not control over the browser. If it was to scan via javascript it's not currently running on the frontend of the page so there would need to be some parsing and access to the page dom via a URL.

**Comment by amberhinds** [comment]
OK, I will just note for now that we're not currently checking font sizing when em or rem is being used in the documentation.
